Adrien/hide show mount point
muesli/duf pull request #107
Opened 2021-02-20 22:06 UTC by IGLOU-EU

Fix #101

2021-02-24 15:52 UTC, luckman212 commented
Possible to add wildcard support?

```
duf -hide-mp '/Volumes/.timemachine*'
```
or
```
duf -only-mp '/System/Volumes/*'
```

2021-02-24 21:01 UTC, IGLOU-EU commented
Hi @luckman212 
this is a good idea, I can do that.

2021-03-27 20:00 UTC, IGLOU-EU commented
Add `*` support for pattern matching
Requested by #106

2021-03-28 02:04 UTC, muesli requested changes
Nice! Sorry for all the nitpicky typo comments :smiley:

2021-03-28 02:04 UTC, muesli commented on main.go
> +	// if pattern is a wildcar or
Typo in `wildcard`.

2021-03-28 02:04 UTC, muesli commented on main.go
> +	// if parttern ans str are equal
Typo in `pattern`.

2021-03-28 02:04 UTC, muesli commented on main.go
> +	// if pattern not contain a wildcar or
Typo in `wildcard` and `pattern`.

2021-03-28 02:04 UTC, muesli commented on main.go
> +	// iterate over plited pattern
Typo in `split`.

2021-03-28 02:04 UTC, muesli commented on main.go
> +	hideMp      = flag.String("hide-mp", "", "hide specific mount points, separated with commas (Support Asterisk wildcard)")
We can probably shorten this to just read `(supports wildcards)` or `(supports globs)`.

2021-03-28 02:04 UTC, muesli commented on main.go
> +func match(str, pattern string) bool {
Maybe we can use something like `filepath.Glob` here? https://golang.org/pkg/path/filepath/#Glob

2021-03-28 06:00 UTC, muesli commented
I'm going to rebase master on top of your work, in the hope that it fixes the CI error.

2021-03-28 12:24 UTC, IGLOU-EU commented
> Nice! Sorry for all the nitpicky typo comments 😃

Ho ... I'm so sorry about that 😖

2021-03-28 12:47 UTC, IGLOU-EU commented on main.go
> +	hideMp      = flag.String("hide-mp", "", "hide specific mount points, separated with commas (Support Asterisk wildcard)")
That not match globs and this is not a full wildcard matcher     
Wildcard is `*` and `?`, we only match `*`   
I can add `?` support, but the code grow exponentially, and I think is not useful in this case

🤔

2021-03-28 12:55 UTC, IGLOU-EU commented on main.go
> +func match(str, pattern string) bool {
I think we can't,
pkg path/filepath have `Glob` and `Match`, very cool function.
But can't match `/` in pattern ...

The Only solution is to replace `/` or `\` by something else like `&`
That can be cool, and match more than `*` ... 
```go
fmt.Println(filepath.Match("*catch&*", "&home&catch&foo")) // Return true
fmt.Println(filepath.Match("*catch/*", "/home/catch/foo")) // Return false
```

Tell me if you think this is a better solution 😃

2021-03-28 13:02 UTC, muesli commented on main.go
> +func match(str, pattern string) bool {
I think that's fine as long as you follow its syntax:

```go
fmt.Println(filepath.Match("/*/catch/*", "/home/catch/foo")) // Returns true
```

2021-03-28 13:08 UTC, IGLOU-EU commented on main.go
> +func match(str, pattern string) bool {
Of course, but on #106 and #112 you can see sub path mount point. 
Like the simplest `/run/*`, can't match every mount point

2021-03-28 13:15 UTC, muesli commented on main.go
> +func match(str, pattern string) bool {
I see. In that case https://github.com/gobwas/glob or https://github.com/goreleaser/fileglob could be useful. Alternatively, if we use our own matcher, we should probably add a couple of tests for it, as this is typically rather error-prone and fragile code.

2021-03-28 13:33 UTC, IGLOU-EU commented on main.go
> +func match(str, pattern string) bool {
I'm not understood about `fileglob` this lib find in directory only, not string/pattern.
`glob.go` with compiled list can be a good alternative 🤔 
That is true, pattern matching produce tricky code ... I can create a light wildcard lib, with doc, coverage and report 🤔

2021-03-28 14:36 UTC, IGLOU-EU commented on main.go
> +func match(str, pattern string) bool {
Pkg wildcar from Minio can be great and light
https://github.com/minio/minio/tree/master/pkg/wildcard

What do you think ?

2021-03-28 15:02 UTC, muesli commented on main.go
> +func match(str, pattern string) bool {
It looks solid, but the minio package is sadly a bigger dependency (that comes with its own dependencies on top). Another approach I like is this one: https://github.com/mattn/go-zglob

Just for the record, I'm really not opposed to your implementation. We could definitely play with that, we should probably just move it to a separate file and add a few tests for it. The only downside I see is not supporting other common globing mechanisms, which people may expect to work as well.

2021-03-28 15:07 UTC, IGLOU-EU commented on main.go
> +func match(str, pattern string) bool {
I have made a benchmark, my solution is pretty bad ^^
But minio is the best and match all wildcard.
```
BenchmarkMyWildcard-8            	 2257731	       538.9 ns/op	     232 B/op	       6 allocs/op
BenchmarkMinioWildcard-8         	11347909	       106.4 ns/op	       0 B/op	       0 allocs/op
BenchmarkMinioWildcardSimple-8   	11510710	       103.9 ns/op	       0 B/op	       0 allocs/op
BenchmarkGoGloboWildcard-8       	 8805710	       135.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkGoGloboWildcardBig-8    	  368943	      3312 ns/op	    1944 B/op	      53 allocs/op
```

2021-03-28 16:34 UTC, IGLOU-EU commented on main.go
> +func match(str, pattern string) bool {
@muesli https://github.com/IGLOU-EU/go-wilcard ? 😺

2021-03-29 07:00 UTC, muesli commented on go.sum
> +git.iglou.eu/Imported/go-wilcard v1.0.0 h1:3Vb9TZPZYcZ8uEJRcbJmE1ne0cErVj6laAjkq58dtGY=
Is this a private server of yours? Be aware that this may cause *a lot* of hits on your server. I'm all for self-hosting, but here I'd like to suggest to actually use the Github mirror of your project.

2021-03-29 07:02 UTC, muesli commented on main.go
> +	hideMp      = flag.String("hide-mp", "", "hide specific mount points, separated with commas (Support Asterisk wildcard)")
If I understood you correctly go-wildcard solves this and we can actually refer to just `wildcards` or `globs`?

2021-03-29 07:02 UTC, muesli commented on main.go
> +func match(str, pattern string) bool {
Looks good at a first glance! :heart:

2021-03-29 13:59 UTC, IGLOU-EU commented on go.sum
> +git.iglou.eu/Imported/go-wilcard v1.0.0 h1:3Vb9TZPZYcZ8uEJRcbJmE1ne0cErVj6laAjkq58dtGY=
That is true, `replace` in `go mod` added !

2021-03-31 21:25 UTC, IGLOU-EU commented on main.go
> +	hideMp      = flag.String("hide-mp", "", "hide specific mount points, separated with commas (Support Asterisk wildcard)")
go-wildcard solves this and can actually refer to wildcards, like requested on issue :p

2021-04-02 15:19 UTC, IGLOU-EU commented
this is ok for you @muesli ?

2021-04-03 09:32 UTC, muesli commented
Will give it one final review today!

2021-04-09 05:37 UTC, muesli commented
Ok, played with this and it's looking good. However on my first try I fell for a trap:

```bash
duf --only-mp /foobar/*
```

This of course uses the shell's globbing and delivers unexpected results. I'm thinking we'll need to provide some examples in the README and point out that caveat, to avoid confusion. I'll take care of this and push some updates to your branch, which should finally finish this up.

Thank you for your contribution and all the work involved!

2021-04-09 05:55 UTC, muesli commented on go.mod
> +	git.iglou.eu/Imported/go-wilcard v1.0.0
Ooops, noticed a typo in the repo name: `go-wilcard`.

2021-04-09 10:35 UTC, IGLOU-EU commented on go.mod
> +	git.iglou.eu/Imported/go-wilcard v1.0.0
Ho ... my ...

2021-04-14 17:40 UTC, IGLOU-EU commented
Thank you for your time and review. Many would like to get more involved in Free Software, and it's with people like you that we can :)

2021-04-14 18:02 UTC, muesli commented
> Thank you for your time and review. Many would like to get more involved in Free Software, and it's with people like you that we can :)

I'm glad to hear you enjoy contributing to open-source! Looking forward to many more contributions!

Will give this a final review before this weekend and merge it!

2021-04-21 08:36 UTC, muesli approved these changes
LGTM! Thank you!

2021-04-21 10:23 UTC, merged