Fix the duplicate of the result list
muesli/duf pull request #209
Opened 2022-10-24 11:17 UTC by Lan-ce-lot

Signed-off-by: Lancelot [1984737645@qq.com](mailto:1984737645@qq.com)

### Describe what this PR does / why we need it

Fix the duplicate of the result list.

### Does this pull request fix one issue?

Fixes #190.

### Describe how you did it

By using a hash table to Record the filesystem that appears, if the filesystem already exists, it doesn't append.

### Describe how to verify it

<img width="194" alt="image" src="https://user-images.githubusercontent.com/53330071/197513962-e4adcb02-ac4f-4324-8167-e3ce3b269f90.png">

Before

<img width="773" alt="image" src="https://user-images.githubusercontent.com/53330071/197513260-d3d2b637-21ff-43b0-8650-cd8c2d37e8ce.png">

after de-duplicated the resulting list.

<img width="759" alt="image" src="https://user-images.githubusercontent.com/53330071/197513201-6d0d7985-8861-47b9-a7ed-c2c78379616b.png">

### Special notes for reviews

2022-10-25 00:32 UTC, muesli requested changes
Just small cleanups, looks good otherwise!

2022-10-25 00:32 UTC, muesli commented on main.go
> +		vis := make(map[string]bool)
It doesn't make much difference in this particular case, but generally speaking, you can use a `map[string]struct{}`, which avoids the extra allocation for a bool.

2022-10-25 00:32 UTC, muesli commented on main.go
> +					tmp = append(tmp, v)
Instead of keeping a temporary slice, we can just directly append to `mounts` here.

2022-10-25 08:13 UTC, Lan-ce-lot commented on main.go
> +					tmp = append(tmp, v)
Thank you for your suggestion, I have modified it

2022-10-30 13:33 UTC, Lan-ce-lot commented
> Just small cleanups, looks good otherwise!

PTAL

2023-03-28 06:02 UTC, gj67668838 commented
sounds good.

2024-03-03 13:26 UTC, C0rn3j commented
@muesli Anything else this needs?

2025-08-25 06:10 UTC, muesli approved these changes

2025-08-28 00:29 UTC, merged