Add --hide-fs to hide specific fs types
muesli/duf pull request #38
Opened 2020-09-29 05:27 UTC by RangerCD

Solves #12 

Example:
```
duf --hide-fs=tmpfs,overlay
```

2020-09-30 08:42 UTC, AverageMarcus commented on main.go
> +		hideMap[fs] = struct{}{}
Might be worth ensureing the inputted filetypes are converted to lowercase: e.g.
```suggestion
		hideMap[strings.ToLower(fs)] = struct{}{}
```

2020-09-30 09:23 UTC, RangerCD commented on main.go
> +		hideMap[fs] = struct{}{}
Not pretty sure whether this value is case-sensitive. 

https://man7.org/linux/man-pages//man5/fs.5.html
> ```
> FILESYSTEMS(5)             Linux Programmer's Manual            FILESYSTEMS(5)
>
> NAME
>        filesystems  -  Linux  filesystem  types:  ext, ext2, ext3, ext4, hpfs,
>        iso9660, JFS, minix, msdos, ncpfs nfs, ntfs, proc, Reiserfs, smb, sysv,
>        umsdos, vfat, XFS, xiafs,
> ```

It seems like fs types are case-sensitive according to the description. 
But I'm confused now, since a XFS filesystem shows `xfs` in `Fstype`, but on that man page it says `XFS`.

2020-10-02 00:07 UTC, muesli requested changes
Nice work, almost there! Just a few tiny changes I'd appreciate.

2020-10-02 00:07 UTC, muesli commented on main.go
> +		if len(fs) == 0 {
Similar to `parseColumns` we should probably check the length of the trimmed version of `fs` to prevent input strings like `foo, ,bar` causing problems.

2020-10-02 00:07 UTC, muesli commented on main.go
> +		hideMap[fs] = struct{}{}
Did you come to a conclusion here? Personally I think I agree, purely because users shouldn't be required to type `XFS` or `JFS` (all uppercase) on the command-line. This would probably cause a bunch of confusion, especially if the filtering doesn't apply silently: there wouldn't be an error or any indication that lowercase vs uppercase makes a difference here.

2020-10-02 05:03 UTC, RangerCD commented on main.go
> +		hideMap[fs] = struct{}{}
After an experiment, I found out that the value of `Fstype` **is case-sensitive**. I've managed to create a mount point, with upper-case letter in its type name, by using `hello` example in libfuse.  And this is how I tested:
1. build hello example
2. rename the output binary to `Hello`
3. execute `./Hello /mnt`, or any other mount point

Then `duf --all` shows:
```
...
│ MOUNTED ON               │ SIZE │ USED │ AVAIL │ USE% │ TYPE                   │ FILESYSTEM        │
├──────────────────────────┼──────┼──────┼───────┼──────┼────────────────────────┼───────────────────┤
│ /mnt                     │   0B │   0B │    0B │      │ fuse.Hello             │ Hello             │
...
```

I think it should not be a problem to make `--hide-fs` a case-sensitive flag. In a general scenario, user would specify `--hide-fs` after finding out there are too much unnecessary mount points listed, which means the actual type name is already printed on screen clearly.

2020-10-02 05:18 UTC, RangerCD commented on main.go
> +		if len(fs) == 0 {
Fixed with https://github.com/muesli/duf/pull/38/commits/6b9b6c9c02547a3d752767bc93f68c33f6ce6c90

2020-10-02 20:47 UTC, muesli approved these changes

2020-10-02 20:47 UTC, merged