Add style flag
muesli/duf pull request #54
Opened 2020-10-04 06:27 UTC by rossdeane

Solves #49 

Adds `--style` flag to support terminals that can't display unicode characters, allows use of ASCII chars instead.

2020-10-05 21:54 UTC, muesli requested changes

2020-10-05 21:54 UTC, muesli commented on main.go
> +		printTable("local", local, sortCol, columns, *style)
I think it would be preferable to have a helper method that converts the user-provided string (`ascii` or `unicode`) to the table style type, so we can pass the correct value to `printTable` here. It should probably also print out an error and exit if the given style is an unknown string.

I already merged your other PR, but thinking about it, we should do the same for unknown theme names, too.

2020-10-06 19:20 UTC, rossdeane commented on main.go
> +		printTable("local", local, sortCol, columns, *style)
Cool, something like that? Not sure if that helper belongs in table.go?

2020-10-06 23:51 UTC, muesli requested changes
Almost there!

2020-10-06 23:51 UTC, muesli commented on main.go
> +	var style, err = getTableStyle(*styleOpt)
I would move this to the `main` method, right below the theme parsing. They kinda belong together, I think. I would probably call it `parseStyle` to be in line with the other method names.

2020-10-06 23:51 UTC, muesli commented on table.go
> +// getTableStyle converts user-provided style option into a table.Style.
Move this method to main.go, below `parseColumns` and call it `parseStyle` or `parseTableStyle`.

2020-10-07 14:09 UTC, muesli commented on main.go
> +<<<<<<< HEAD
Whoops, merge conflict :smile:

2020-10-07 19:01 UTC, rossdeane commented on main.go
> +<<<<<<< HEAD
I know, I tried a rebase before coffee and then was afk for the day 😄 
Will sort tomorrow.

2020-10-09 01:39 UTC, muesli commented on main.go
> +<<<<<<< HEAD
Fixed this for you.

2020-10-09 01:42 UTC, merged