Support json output parsing via jq
muesli/duf pull request #8
Opened 2020-09-21 12:40 UTC by ansrivas

This pull request fixes #7 

- with new option --json-output json output is rendered on the screen
- updated README.md

2020-09-22 12:11 UTC, ansrivas commented
@muesli hi thanks for the project, would you like me to change/improve something with the pull-request?

2020-09-22 14:44 UTC, muesli commented
Thanks for the PR, will review tonight!

2020-09-23 12:35 UTC, muesli requested changes

2020-09-23 12:35 UTC, muesli commented on README.md
> +    duf  --json-output | jq
Careful, this would be `-json-output` (only one dash).

2020-09-23 12:35 UTC, muesli commented on main.go
> +	mounts.All = make(map[string][]Mount)
I'm not a fan of "stringly typing" this. Why not use separate members `local`, `network`, ...?

2020-09-23 12:35 UTC, muesli commented on mounts.go
> +		return nil, warnings, err
You can simply return nil here instead of the empty `warnings` slice.

2020-09-23 12:35 UTC, muesli commented on mounts.go
> +			return nil, warnings, fmt.Errorf("found invalid mountinfo line in file %s: %s ", filename, line)
Same here: return nil instead of an empty slice.

2020-09-23 12:59 UTC, ansrivas commented on README.md
> +    duf  --json-output | jq
Thank you for the review, both formats work when you parse flags. For consistency of the readme, I will change it to single `-`
```
✦ ❯ ./duf --json-output | jq .Warnings
[
  "/var/lib/docker/overlay2/c54999db0d5a7614b5a750717622707eba3a4146eb9fcef42959d84872258fe6/merged: permission denied",
  "/var/lib/docker/containers/fd297153a00e89e7dc4dae9b4b9f133bbeed7bb36169c71b0589646ac90076d3/mounts/shm: permission denied",
  "/run/docker/netns/f93947139ed9: permission denied"
]

```

2020-09-23 13:01 UTC, ansrivas commented on main.go
> +	mounts.All = make(map[string][]Mount)
Just merged it such that its easier to dump the json output in one go, how do you prefer to do this? Individually generating the json string and then appending in the end?

2020-09-23 15:09 UTC, muesli commented on main.go
> +	mounts.All = make(map[string][]Mount)
That's a good question. On the one hand it would be nice to split the output into mount-groups even on the JSON-side, on the other hand it may be better to simply add a flag like `network: true` to the JSON output struct (which may or may not have to be a separate struct then).

2020-09-23 15:35 UTC, ansrivas commented on main.go
> +	mounts.All = make(map[string][]Mount)
Please correct me if I understood this wrong. 
I think what you are describing here is already the default behaviour.

```yaml
✦ ❯ ./duf -json-output | jq -r keys[] 
Mounts
Warnings

```
And then inside `Mounts` the keys are:
```yaml
✦ ❯ ./duf -json-output | jq -r '.Mounts | keys[]'
FUSE devices
local devices
network devices
special devices

```
or fetching a particular device
```yaml
✦ ❯ ./duf -json-output | jq -r '.Mounts."local devices"'
[...]
```

2020-09-23 16:25 UTC, muesli commented on main.go
> +	mounts.All = make(map[string][]Mount)
The last example you gave is a good one. Here, I think I'd rather do (from a JSON consumer's point):

```
/duf -json-output | jq -r '.Mounts.local'
/duf -json-output | jq -r '.Mounts.network'
```

Alternatively we could simply return all mounts inside `Mounts`, with boolean flags like `local:true`, `network: true`, etc.

2020-09-23 17:26 UTC, ansrivas commented on main.go
> +	mounts.All = make(map[string][]Mount)
As a user consuming json, I think first one looks pretty straight forward.

```yaml
✦ ❯ ./duf -json-output | jq -r '.Mounts | keys[]'
FUSE
local
special

## Now this becomes straight forward based on the keys from previous output
✦ ❯ ./duf -json-output | jq -r '.Mounts.local'
```

( In case the second option is preferred, I'd recommend having a field like `type: network`, `type: local`   or `devicetype: network`, such that one can write more concise logic around the `type` field and process it further)

2020-09-23 17:41 UTC, muesli commented
@ansrivas Just a heads up, I will rebase master into your branch and push a few changes to it in the next hour or two - if you don't mind?

2020-09-23 18:02 UTC, ansrivas commented
> @ansrivas Just a heads up, I will rebase master into your branch and push a few changes to it in the next hour or two - if you don't mind?

Sure, no problem.

2020-09-23 19:16 UTC, muesli commented on main.go
> +	suffix := "device"
Just a heads up: love the change, but we should try to keep such things in separate PRs, making it easier to digest individual PRs.

2020-09-23 20:18 UTC, muesli commented
Ok, I've pushed my changes. I've decided to simplify the JSON rendering a bunch: it now simply dumps _all_ available information to stdout. This means parameters like "-hide-special" won't have an effect anymore.

This is intentional though: filtering the JSON data is easy enough, and it would only become cumbersome to re-implement all other view settings in the JSON marshaller.

2020-09-23 21:37 UTC, merged